/** @type {import('style-dictionary').Config} */
export default {
  source: ["src/tokens/**/*.json"],
  platforms: {
    css: {
      transformGroup: "css",
      buildPath: "dist/css/",
      files: [
        {
          destination: "tokens.css",
          format: "css/variables",
          options: {
            selector: ":root",
            showFileHeader: true,
          },
        },
      ],
    },
    js: {
      transformGroup: "js",
      buildPath: "dist/",
      files: [
        {
          destination: "theme.mjs",
          format: "tailwind/theme",
          options: { showFileHeader: true },
        },
      ],
    },
  },
  hooks: {
    formats: {
      "tailwind/theme": ({ dictionary }) => {
        const theme = {};
        for (const token of dictionary.allTokens) {
          let obj = theme;
          const path = token.path;
          for (let i = 0; i < path.length - 1; i++) {
            const key = path[i];
            if (!Object.prototype.hasOwnProperty.call(obj, key)) obj[key] = {};
            obj = obj[key];
          }
          obj[path[path.length - 1]] = token.value;
        }
        const header = `/**
 * Design tokens for Tailwind theme.extend
 * Generated by Style Dictionary. Do not edit directly.
 */
`;
        return header + "export default " + JSON.stringify(theme, null, 2) + ";\n";
      },
    },
  },
};
